name: 'Build'

on:
  pull_request:
  pull_request_target:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the merged commit from PR and base branch
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          # repository: ${{ github.event.pull_request.head.repo.full_name }}
          # ref: ${{ github.event.pull_request.head.ref }}
          # ref: refs/pull/${{ github.event.pull_request.number }}/merge
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Checkout the head commit of the branch
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2

      - name: 'Run Build'
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/abatishchev/OpenSource
          azure-pipeline-name: 'Jwt.Net-CI'
          # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
